### ISSUE TITLE
Umbrella Project

### ISSUE THREAD

**Issue by hisapy** [iporaitech/pwr2-docker#14]
Make the Elixir/Phoenix project an Umbrella Project and  implement some [relay-examples](https://github.com/relayjs/relay-examples) each as an umbrella child project.

UPDATE:

As discussed in Scrum, initially the only apps in the umbrella will be:
1. **webapp**: Will be responsible of the web front-end, the Phoenix app including all the assets (css, js, images).
2. **start_wars**.  Will be responsible of providing the types and db for the StarWars example.

**Comment by hisapy** [comment]
@edipox I believe #9 is somehow related to this, or perhaps the same thing

**Comment by edipox** [comment]
06bbd266f9faf7d4b1bcfc280dee7d27e09a4b48 closes this issue
