### ISSUE TITLE
Documentation Project

### ISSUE THREAD

**Issue by hisapy** [iporaitech/pwr2-docker#25]
Provide documentation to be hosted inside the project in such a way that you can access different sections from navigation, such as:
- Guides
- Examples
- API Reference
- Other docs section

**Comment by rsjavier14** [comment]
hello, the idea is to use markdown for documentation. I have two options, which are: [react-markdown](https://github.com/rexxars/react-markdown) and [markdown-loader](https://github.com/peerigon/markdown-loader).
They are easy to use and meets what is needed, but one of them had trouble loading styles ([markdown-loader](https://github.com/peerigon/markdown-loader)). 
What do you think @hisapy , @edipox ? They have other ideas or suggestions?

**Comment by hisapy** [comment]
As discussed in Skype, go for the one without the styling issues ... Waiting for your pull request to see how it goes :)
